### PR TITLE
Change welcome text

### PR DESCRIPTION
**Pull request by yaya-galah**
re #1

### CODE REVIEW

**Comment by monkeypants** [comment]
thanks for the change @yaya-galah, it's much better!

**Comment by yaya-galah** [comment]
Thank you!

**Comment by yaya-galah** [comment]
I like to type on my computer. It's fun

**Comment by yaya-galah** [comment]
BTW what is the web site name again?

**Comment by monkeypants** [comment]
https://chookamatronics.github.io/gledden-st-eggs/

**Comment by yaya-galah** [comment]
thanks.

**Comment by yaya-galah** [comment]
It looks pretty good so far...

**Comment by yaya-galah** [comment]
what do we do now??

**Comment by yaya-galah** [comment]
Hello?

**Comment by yaya-galah** [comment]
My pocket money industries isn't working. Can you please come over here and look at it??

**Comment by yaya-galah** [comment]
Good work team, we had a very successfull mission today!

**Comment by yaya-galah** [comment]
Wow. This is going really well. I can't belive that you made  whole two new pages in one night!!

**Comment by yaya-galah** [comment]
Hello Monkeypants!!

**Comment by monkeypants** [comment]
If you put @monkeypants it will send me a message.

**Comment by monkeypants** [comment]
(see the circa simbol, "@")

**Pull request merged**
